<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/tr/html4/loose.dtd">
<html>
<head>
	<!-- Generated by chxdoc (build 511) on 2009-05-25 -->
	<title>Assertation (uTest)</title>
	<meta name="date" content="2009-05-25"/>
	<meta name="keywords" content="utest.Assertation enum"/>
	<link href="../../stylesheet.css" type="text/css" rel="stylesheet"/>

<script type="text/javascript">
function windowTitle()
{
    if (location.href.indexOf('is-external=true') == -1) {
        parent.document.title="Assertation (uTest)";
    }
}
</script>
<noscript></noscript>
</head>
<body onload="windowTitle();">
	<div class="type-frame" id="enum-frame">
	<!-- ======== START OF class DATA ======== -->
	<h1 class="enum">utest.Assertation</h1>
	<dl>
		<dt>available in</dt>
		<dd>neko, php, flash9, flash8, flash7, flash6</dd>
	</dl>

	<div class="doc">
			<!-- Comment block -->
			
 Enumerates the states available as a result of
 invoking one of the static methods of @see {@link utest.Assert}.

				</div>

	<!-- ========= CONSTRUCTOR DETAIL ======== -->
	<div class="members-panel">
		<h2><a name="constructor_detail"></a>Constructors</h2>
		<div class="members">
			<div class="member">
				<div class="header">
		<a name="AsyncError()"></a><span class="name">AsyncError</span>(e : <a href="../Dynamic.html" class="type">Dynamic</a>)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>e:</code> The captured error/exception</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 An error has occurred during an asynchronous test.</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="Error()"></a><span class="name">Error</span>(e : <a href="../Dynamic.html" class="type">Dynamic</a>)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>e:</code> The captured error/exception</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 An error has occurred during the execution of the test that prevents
	 futher assertion to be tested.</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="Failure()"></a><span class="name">Failure</span>(msg : <a href="../String.html" class="type">String</a>,pos : haxe.PosInfos)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>msg:</code> An error message containing the reasons for the failure.</dd>
									<dd><code>pos:</code> Code position where the Assert call has been executed</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 Assertion is a falure. This does not denote an error in the assertion
	 code but that the testing condition has failed for some reason.
	 Ei.: Assert.isTrue(1 == 0);</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="SetupError()"></a><span class="name">SetupError</span>(e : <a href="../Dynamic.html" class="type">Dynamic</a>)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>e:</code> The captured error/exception</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 An error has occurred during the Setup phase of the test. It prevents
	 the test to be run.</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="Success()"></a><span class="name">Success</span>(pos : haxe.PosInfos)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>pos:</code> Code position where the Assert call has been executed</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 Assertion is succesful</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="TeardownError()"></a><span class="name">TeardownError</span>(e : <a href="../Dynamic.html" class="type">Dynamic</a>)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>e:</code> The captured error/exception</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 An error has occurred during the Teardown phase of the test.</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="TimeoutError()"></a><span class="name">TimeoutError</span>(missedAsyncs : <a href="../Int.html" class="type">Int</a>)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>missedAsyncs:</code> The number of asynchronous calls that was expected to be performed before the timeout. </dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 The asynchronous phase of a test has gone into timeout.</div>
		</div>
			</div>
					<div class="member">
				<div class="header">
		<a name="Warning()"></a><span class="name">Warning</span>(msg : <a href="../String.html" class="type">String</a>)
	</div>
				<div class="body">
			<dl>
				<!-- deprecated -->
				<!-- type params -->
				<!-- method call parameters -->
					<dt>parameters:</dt>
					<dd><code>msg:</code> The reason behind the warning</dd>
											<!-- method return types comments -->
				<!-- method throws -->
				<!-- requires -->
				<!-- see -->
				<!-- todo -->
				<!-- authors -->
					<!-- platforms -->
					</dl>
			<!-- Comment block -->
		<div class="comment">
	 A warning state. This can be declared explicitely by an Assert call
	 or can denote a test method that contains no assertions at all.</div>
		</div>
			</div>
				</div>
	</div>

	</div>
<!-- ========= END OF ENUM DATA ========= -->
	
</body>
</html>
